version: '3.7'
  pb-integration:
    image: bobobo/pb-integration:latest
    env_file:
      - ./variables.env
    depends_on:
      - app-sync-users-ms
    ports:
      - 10080:8080
    logging:
      driver: json-file
    volumes:
      - pb-log-vol:/home/app/logs
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 200MB
      restart_policy:
        condition: on-failure

#PLEASE NOTE!  dirs for volumes must be created
volumes:
  pb-log-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/appuser/pb-integration/logs/app-sync
      o: bind

networks:
  backend: