version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    env_file:
    - ./variables.env
    ports:
    - 5432:5432
    volumes:
    - db-vol:/var/lib/postgresql/data
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

  postgres-admin-web-ui:
    image: dpage/pgadmin4
    env_file:
    - ./variables.env
    volumes:
    - pg-admin-vol:/var/lib/pgadmin
    networks:
    - backend
    ports:
    - 5050:80
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

  pb-integration:
    image: bobobo/pb-integration:latest
    env_file:
    - ./variables.env
    depends_on:
    - postgres
    ports:
      - 10080:8080
    logging:
      driver: json-file
    volumes:
      - pb-log-vol:/home/app/logs
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 192MB
      restart_policy:
        condition: on-failure

#PLEASE NOTE!  dirs for volumes must be created
volumes:
  pb-log-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/appuser/pb-integration/logs
      o: bind

  db-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/appuser/pb-integration/database
      o: bind

  pg-admin-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/appuser/pb-integration/pg-web-admin
      o: bind

networks:
  backend: