version: '3.7'
services:
  pb-integration:
    image: bobobo/pb-integration-aws:latest
    env_file:
      - ./variables.env
    ports:
      - 10080:8080
    logging:
      driver: json-file
    volumes:
      - pb-aws-log-vol:/home/app/logs
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 150MB
      restart_policy:
        condition: on-failure
  watchtower:
    image: containrrr/watchtower
    networks:
      - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25MB
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#PLEASE NOTE!  dirs for volumes must be created
volumes:
  pb-aws-log-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/appuser/pb-sync-aws/logs
      o: bind

networks:
  backend: