version: '3'
services:
    pb-24-integration:
        container_name: pb-integration
        image: bobobo/pb-integration:latest
        env_file:
          - ./variables.env
        ports:
            - 10080:8080
        restart: on-failure
        logging:
            driver: json-file
        volumes:
            - ~/pb/logs/:/var/log/pb-integration/
            - ~/pb/db/:/root/db/

    watchtower:
      container_name: watchtower-updater
      image: v2tec/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/config.json
      command: --cleanup --interval 30
      restart: on-failure

    portainer:
      container_name: portainer-web-ui
      image: portainer/portainer
      ports:
      - 9000:9000
      command: -H unix:///var/run/docker.sock
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/pb/portainer_data:/data