version: '3.7'
services:
  pb-integration:
    image: bobobo/pb-integration:latest
    env_file:
    - ./variables.env
    ports:
    - 10080:8080
    logging:
      driver: json-file
    volumes:
    - pb-log-vol:/var/log/pb-integration
    - pb-db-vol:/root/db
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 350MB
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-vol:/prometheus
    depends_on:
    - pb-integration
    networks:
    - backend
    #    ports:
    #    - 9090:9090
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 250MB
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana-vol:/var/lib/grafana
    depends_on:
    - prometheus
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 250MB
      restart_policy:
        condition: on-failure

networks:
  backend:

volumes:
  prometheus-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/prometheus
      o: bind

  grafana-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/grafana
      o: bind

  pb-log-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/logs
      o: bind

  pb-db-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/db
      o: bind
