version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    env_file:
    - ./variables.env
    ports:
    - 5432:5432
    volumes:
    - db-vol:/var/lib/postgresql/data
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

  postgres-admin-web-ui:
    image: dpage/pgadmin4
    env_file:
    - ./variables.env
    volumes:
    - pg-admin-vol:/var/lib/pgadmin
    networks:
    - backend
    ports:
    - 5050:80
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

  pb-integration:
    image: bobobo/pb-integration:latest
    env_file:
    - ./variables.env
    depends_on:
    - postgres
    ports:
      - 10080:8080
    logging:
      driver: json-file
    volumes:
    - pb-log-vol:/var/log/pb-integration
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 192MB
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-vol:/prometheus
    depends_on:
    - pb-integration
    networks:
    - backend
    #    ports:
    #    - 9090:9090
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana-vol:/var/lib/grafana
    depends_on:
    - prometheus
    networks:
    - backend
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 100MB
      restart_policy:
        condition: on-failure

#PLEASE NOTE!  dirs for volumes must be created
volumes:
  prometheus-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/prometheus
      o: bind

  grafana-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/grafana
      o: bind

  pb-log-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/logs
      o: bind

  db-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/database
      o: bind

  pg-admin-vol:
    driver: local
    driver_opts:
      type: none
      device: /app/pg-web-admin
      o: bind

networks:
  backend: