global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'pb-integration'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['pb-integration:8080'] # IP or service name from docker-compose
    labels:
      application: pb-integration