//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.22 at 01:11:10 AM EEST 
//


package com.github.storytime.model.pb.jaxb.account.response;

import javax.xml.bind.annotation.XmlRegistry;



/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@Deprecated
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.Data }
     */
    public Response.Data createResponseData() {
        return new Response.Data();
    }

    /**
     * Create an instance of {@link Response.Data.Info }
     */
    public Response.Data.Info createResponseDataInfo() {
        return new Response.Data.Info();
    }

    /**
     * Create an instance of {@link Response.Data.Info.Cardbalance }
     */
    public Response.Data.Info.Cardbalance createResponseDataInfoCardbalance() {
        return new Response.Data.Info.Cardbalance();
    }

    /**
     * Create an instance of {@link Response.Merchant }
     */
    public Response.Merchant createResponseMerchant() {
        return new Response.Merchant();
    }

    /**
     * Create an instance of {@link Response.Data.Info.Cardbalance.Card }
     */
    public Response.Data.Info.Cardbalance.Card createResponseDataInfoCardbalanceCard() {
        return new Response.Data.Info.Cardbalance.Card();
    }

}
