//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.22 at 01:11:10 AM EEST 
//


package com.github.storytime.model.pb.jaxb.account.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import javax.xml.bind.annotation.*;


@Data
@Accessors(chain = true)
@AllArgsConstructor
@NoArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "merchant",
        "data"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected Response.Merchant merchant;

    @XmlElement(required = true)
    protected Response.Data data;

    @XmlAttribute(name = "version")
    protected Float version;

    @lombok.Data
    @Accessors(chain = true)
    @AllArgsConstructor
    @NoArgsConstructor
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "oper",
            "info"
    })
    public static class Data {

        @XmlElement(required = true)
        protected String oper;

        @XmlElement(required = true)
        protected Response.Data.Info info;

        @lombok.Data
        @Accessors(chain = true)
        @AllArgsConstructor
        @NoArgsConstructor
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "cardbalance"
        })
        public static class Info {

            @XmlElement(required = true)
            protected Response.Data.Info.Cardbalance cardbalance;

            @lombok.Data
            @Accessors(chain = true)
            @AllArgsConstructor
            @NoArgsConstructor
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "card",
                    "avBalance",
                    "balDate",
                    "balDyn",
                    "balance",
                    "finLimit",
                    "tradeLimit"
            })
            public static class Cardbalance {

                @XmlElement(required = true)
                protected Response.Data.Info.Cardbalance.Card card;

                @XmlElement(name = "av_balance")
                protected float avBalance;

                @XmlElement(name = "bal_date")
                protected String balDate;

                @XmlElement(name = "bal_dyn")
                protected String balDyn;

                protected float balance;

                @XmlElement(name = "fin_limit")
                protected float finLimit;

                @XmlElement(name = "trade_limit")
                protected float tradeLimit;

                @lombok.Data
                @Accessors(chain = true)
                @AllArgsConstructor
                @NoArgsConstructor
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "account",
                        "cardNumber",
                        "accName",
                        "accType",
                        "currency",
                        "cardType",
                        "mainCardNumber",
                        "cardStat",
                        "src"
                })
                public static class Card {

                    protected long account;

                    @XmlElement(name = "card_number")
                    protected long cardNumber;

                    @XmlElement(name = "acc_name")
                    protected String accName;

                    @XmlElement(name = "acc_type")
                    protected String accType;

                    @XmlElement(required = true)
                    protected String currency;

                    @XmlElement(name = "card_type")
                    protected String cardType;

                    @XmlElement(name = "main_card_number")
                    protected long mainCardNumber;

                    @XmlElement(name = "card_stat")
                    protected String cardStat;

                    @XmlElement(required = true)
                    protected String src;

                }
            }
        }
    }


    @lombok.Data
    @Accessors(chain = true)
    @AllArgsConstructor
    @NoArgsConstructor
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id",
            "signature"
    })
    public static class Merchant {

        protected int id;

        @XmlElement(required = true)
        protected String signature;

    }
}
