version: 2
jobs:
  build_prod_artifact:
    docker:
      - image: cimg/openjdk:16.0.0
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3072m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3072m"'
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - run:
          name: Build
          command: ./gradlew clean build -x test
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: build-cache-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs/pb-integration.jar
          destination: pb-integration.jar
      - store_artifacts:
          path: Dockerfile
          destination: Dockerfile

  build_prod_docker_image:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3072m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3072m"'
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Get artifacts list
          command: curl https://circleci.com/api/v1.1/project/bitbucket/boevry/pb-integration/$(( $CIRCLE_BUILD_NUM - 1 ))/artifacts?circle-token=$CIRCLE_TOKEN | grep -o 'https://[^"]*' > ~/project/artifacts.txt
      - run:
          name: Download and move artifacts
          command: |
            <artifacts.txt xargs -P4 -I % wget %
            mkdir -p ~/project/build/libs/
            mv pb-integration.jar ~/project/build/libs/
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build docker image
          command: docker build -t bobobo/pb-integration:$(( $CIRCLE_BUILD_NUM - 1 )) -t bobobo/pb-integration:latest .
      - run:
          name: Tag docker image
          command: docker tag bobobo/pb-integration:$(( $CIRCLE_BUILD_NUM - 1 )) bobobo/pb-integration:latest
      - run:
          name: Push docker image
          command: docker push bobobo/pb-integration:latest && docker push bobobo/pb-integration:$(( $CIRCLE_BUILD_NUM - 1 ))

  ### DEVELOP (clean build and do sonar tests)
  build_and_verify_on_sonar:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx3072m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3072m"'
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - run: ### Free sonar cloud can analyze only one branch
          name: Build and verify on sonar
          command: ./gradlew clean sonarqube -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN build
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: build-cache-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build_and_verify_on_sonar_flow:
    jobs:
      - build_and_verify_on_sonar:
          filters:
            branches:
              only:
                - develop
  build_prod_flow:
    jobs:
      - build_prod_docker_image:
          requires:
            - build_prod_artifact
          filters:
            branches:
              only:
                - master
      - build_prod_artifact:
          filters:
            branches:
              only:
                - master