//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 01:26:57 PM EEST 
//


package com.github.storytime.model.jaxb.history.response.ok;

import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "merchant",
        "data"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected Response.Merchant merchant;
    @XmlElement(required = true)
    protected Response.Data data;
    @XmlAttribute(name = "version")
    protected Float version;

    /**
     * Gets the value of the merchant property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Merchant }
     *     
     */
    public Response.Merchant getMerchant() {
        return merchant;
    }

    /**
     * Sets the value of the merchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Merchant }
     *     
     */
    public void setMerchant(Response.Merchant value) {
        this.merchant = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Data }
     *     
     */
    public Response.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Data }
     *     
     */
    public void setData(Response.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="oper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="info">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="statements">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="statement" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="card" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                                     &lt;attribute name="appcode" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="trandate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                                     &lt;attribute name="trantime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *                                     &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="cardamount" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="rest" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="credit" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="debet" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "oper",
            "info"
    })
    public static class Data {

        @XmlElement(required = true)
        protected String oper;
        @XmlElement(required = true)
        protected Response.Data.Info info;

        /**
         * Gets the value of the oper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOper() {
            return oper;
        }

        /**
         * Sets the value of the oper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOper(String value) {
            this.oper = value;
        }

        /**
         * Gets the value of the info property.
         * 
         * @return
         *     possible object is
         *     {@link Response.Data.Info }
         *     
         */
        public Response.Data.Info getInfo() {
            return info;
        }

        /**
         * Sets the value of the info property.
         * 
         * @param value
         *     allowed object is
         *     {@link Response.Data.Info }
         *     
         */
        public void setInfo(Response.Data.Info value) {
            this.info = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="statements">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="statement" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="card" type="{http://www.w3.org/2001/XMLSchema}long" />
         *                           &lt;attribute name="appcode" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="trandate" type="{http://www.w3.org/2001/XMLSchema}date" />
         *                           &lt;attribute name="trantime" type="{http://www.w3.org/2001/XMLSchema}time" />
         *                           &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="cardamount" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="rest" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="credit" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="debet" type="{http://www.w3.org/2001/XMLSchema}float" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "statements"
        })
        public static class Info {

            @XmlElement(required = true)
            protected Response.Data.Info.Statements statements;

            /**
             * Gets the value of the statements property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Data.Info.Statements }
             *     
             */
            public Response.Data.Info.Statements getStatements() {
                return statements;
            }

            /**
             * Sets the value of the statements property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Data.Info.Statements }
             *     
             */
            public void setStatements(Response.Data.Info.Statements value) {
                this.statements = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="statement" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="card" type="{http://www.w3.org/2001/XMLSchema}long" />
             *                 &lt;attribute name="appcode" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="trandate" type="{http://www.w3.org/2001/XMLSchema}date" />
             *                 &lt;attribute name="trantime" type="{http://www.w3.org/2001/XMLSchema}time" />
             *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="cardamount" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="rest" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="credit" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="debet" type="{http://www.w3.org/2001/XMLSchema}float" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "statement"
            })
            public static class Statements {

                protected List<Response.Data.Info.Statements.Statement> statement;
                @XmlAttribute(name = "status")
                protected String status;
                @XmlAttribute(name = "credit")
                protected Float credit;
                @XmlAttribute(name = "debet")
                protected Float debet;

                /**
                 * Gets the value of the statement property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the statement property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStatement().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Response.Data.Info.Statements.Statement }
                 * 
                 * 
                 */
                public List<Response.Data.Info.Statements.Statement> getStatement() {
                    if (statement == null) {
                        statement = new ArrayList<Response.Data.Info.Statements.Statement>();
                    }
                    return this.statement;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the credit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getCredit() {
                    return credit;
                }

                /**
                 * Sets the value of the credit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setCredit(Float value) {
                    this.credit = value;
                }

                /**
                 * Gets the value of the debet property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getDebet() {
                    return debet;
                }

                /**
                 * Sets the value of the debet property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setDebet(Float value) {
                    this.debet = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="card" type="{http://www.w3.org/2001/XMLSchema}long" />
                 *       &lt;attribute name="appcode" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="trandate" type="{http://www.w3.org/2001/XMLSchema}date" />
                 *       &lt;attribute name="trantime" type="{http://www.w3.org/2001/XMLSchema}time" />
                 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="cardamount" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="rest" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "value"
                })
                public static class Statement {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "card")
                    protected Long card;
                    @XmlAttribute(name = "appcode")
                    protected Integer appcode;
                    @XmlAttribute(name = "trandate")
                    @XmlSchemaType(name = "date")
                    protected XMLGregorianCalendar trandate;
                    @XmlAttribute(name = "trantime")
                    @XmlSchemaType(name = "time")
                    protected XMLGregorianCalendar trantime;
                    @XmlAttribute(name = "amount")
                    protected String amount;
                    @XmlAttribute(name = "cardamount")
                    protected String cardamount;
                    @XmlAttribute(name = "rest")
                    protected String rest;
                    @XmlAttribute(name = "terminal")
                    protected String terminal;
                    @XmlAttribute(name = "description")
                    protected String description;

                    @XmlAttribute(name = "description", required = false)
                    protected String customComment;

                    public String getCustomComment() {
                        return customComment;
                    }

                    public Statement setCustomComment(String customComment) {
                        this.customComment = customComment;
                        return this;
                    }

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the card property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Long }
                     *     
                     */
                    public Long getCard() {
                        return card;
                    }

                    /**
                     * Sets the value of the card property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Long }
                     *     
                     */
                    public void setCard(Long value) {
                        this.card = value;
                    }

                    /**
                     * Gets the value of the appcode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getAppcode() {
                        return appcode;
                    }

                    /**
                     * Sets the value of the appcode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setAppcode(Integer value) {
                        this.appcode = value;
                    }

                    /**
                     * Gets the value of the trandate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getTrandate() {
                        return trandate;
                    }

                    /**
                     * Sets the value of the trandate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setTrandate(XMLGregorianCalendar value) {
                        this.trandate = value;
                    }

                    /**
                     * Gets the value of the trantime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getTrantime() {
                        return trantime;
                    }

                    /**
                     * Sets the value of the trantime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setTrantime(XMLGregorianCalendar value) {
                        this.trantime = value;
                    }

                    /**
                     * Gets the value of the amount property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAmount() {
                        return amount;
                    }

                    /**
                     * Sets the value of the amount property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAmount(String value) {
                        this.amount = value;
                    }

                    /**
                     * Gets the value of the cardamount property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCardamount() {
                        return cardamount;
                    }

                    /**
                     * Sets the value of the cardamount property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCardamount(String value) {
                        this.cardamount = value;
                    }

                    /**
                     * Gets the value of the rest property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRest() {
                        return rest;
                    }

                    /**
                     * Sets the value of the rest property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRest(String value) {
                        this.rest = value;
                    }

                    /**
                     * Gets the value of the terminal property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTerminal() {
                        return terminal;
                    }

                    /**
                     * Sets the value of the terminal property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTerminal(String value) {
                        this.terminal = value;
                    }

                    /**
                     * Gets the value of the description property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDescription() {
                        return description;
                    }

                    /**
                     * Sets the value of the description property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDescription(String value) {
                        this.description = value;
                    }

                    @Override
                    public String toString() {
                        return new ToStringBuilder(this)
                                .append("value", value)
                                .append("card", card)
                                .append("appcode", appcode)
                                .append("trandate", trandate)
                                .append("trantime", trantime)
                                .append("amount", amount)
                                .append("cardamount", cardamount)
                                .append("rest", rest)
                                .append("terminal", terminal)
                                .append("description", description)
                                .append("customComment", customComment)
                                .toString();
                    }
                }



            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="signature" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id",
            "signature"
    })
    public static class Merchant {

        protected int id;
        @XmlElement(required = true)
        protected String signature;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the signature property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignature() {
            return signature;
        }

        /**
         * Sets the value of the signature property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignature(String value) {
            this.signature = value;
        }

    }


}
