//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 01:26:58 PM EEST 
//


package com.github.storytime.model.jaxb.history.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.storytime.model.jaxb.history.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.storytime.model.jaxb.history.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Request.Data }
     * 
     */
    public Request.Data createRequestData() {
        return new Request.Data();
    }

    /**
     * Create an instance of {@link Request.Data.Payment }
     * 
     */
    public Request.Data.Payment createRequestDataPayment() {
        return new Request.Data.Payment();
    }

    /**
     * Create an instance of {@link Request.Merchant }
     * 
     */
    public Request.Merchant createRequestMerchant() {
        return new Request.Merchant();
    }

    /**
     * Create an instance of {@link Request.Data.Payment.Prop }
     * 
     */
    public Request.Data.Payment.Prop createRequestDataPaymentProp() {
        return new Request.Data.Payment.Prop();
    }

}
