package com.github.storytime.model.aws;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.UUID;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "sync-app-currency")
public class AwsCurrencyRates {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String currencySource;

    @DynamoDBAttribute
    private String currencyType;

    @DynamoDBAttribute
    private BigDecimal sellRate;

    @DynamoDBAttribute
    private BigDecimal buyRate;

    @DynamoDBAttribute
    private Long dateTime;

}
