package com.github.storytime.model.aws;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
public class AwsMerchant {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String cardNumber;

    @DynamoDBAttribute
    private Integer merchantId;

    @DynamoDBAttribute
    private String password;

    @DynamoDBAttribute
    private Boolean enabled;

    @DynamoDBAttribute
    private Long syncPeriod;

    @DynamoDBAttribute
    private Long syncStartDate;

    @DynamoDBAttribute
    private List<String> awsAdditionalComment;

    @DynamoDBAttribute
    private String shortDesc;
}
