package com.github.storytime.model.aws;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


@DynamoDBTable(tableName = "app-user")
public class AwsUser {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private boolean enabled;

    @DynamoDBAttribute
    private String zenAuthToken;

    @DynamoDBAttribute
    private String timeZone;

    @DynamoDBAttribute
    private Long zenLastSyncTimestamp;

    @DynamoDBAttribute
    private boolean zenSyncEnabled;

    @DynamoDBAttribute
    private String ynabAuthToken;

    @DynamoDBAttribute
    private boolean ynabSyncEnable;

    @DynamoDBAttribute
    private Map<String, String> merchant = new HashMap<>();

//    @DynamoDBAttribute
//    private List<CustomPayee> customPayee = new ArrayList<>();

}
