package com.github.storytime.model.aws;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "sync-app-currency")
public class CurrencyRates {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "currencySource")
    private String currencySource;

    @DynamoDBAttribute(attributeName = "currencyType")
    private String currencyType;

    @DynamoDBAttribute(attributeName = "sellRate")
    private BigDecimal sellRate;

    @DynamoDBAttribute(attributeName = "buyRate")
    private BigDecimal buyRate;

    @DynamoDBAttribute(attributeName = "dateTime")
    private Long dateTime;

}
