package com.github.storytime.model.aws;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBDocument
public class PbMerchant {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "cardNumber")
    private String cardNumber;

    @DynamoDBAttribute(attributeName = "merchantId")
    private Integer merchantId;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "enabled")
    private Boolean enabled;

    @DynamoDBAttribute(attributeName = "syncPeriod")
    private Long syncPeriod;

    @DynamoDBAttribute(attributeName = "syncStartDate")
    private Long syncStartDate;

    @DynamoDBAttribute(attributeName = "awsAdditionalComment")
    private List<String> awsAdditionalComment;

    @DynamoDBAttribute(attributeName = "shortDesc")
    private String shortDesc;
}
