create table currency_rates (
       id BIGINT UNSIGNED generated by default as identity,
        buy_rate decimal(19,2) not null,
        currency_source varchar(255) not null,
        currency_type varchar(255) not null,
        date bigint not null,
        sell_rate decimal(19,2) not null,
        primary key (id)
);

create table merchant_info (
       id BIGINT UNSIGNED generated by default as identity,
        card_number varchar(255) not null,
        enabled boolean not null,
        merchant_id integer not null,
        password varchar(255) not null,
        sync_period bigint not null,
        sync_priority varchar(255),
        sync_start_date bigint not null,
        primary key (id)
);

create table merchant_info_additional_comment (
   merchant_info_id BIGINT UNSIGNED not null,
   additional_comment varchar(255)
);

create table user (
    id BIGINT UNSIGNED generated by default as identity,
    time_zone varchar(255) not null,
    zen_auth_token varchar(255) not null,
    primary key (id)
);

alter table currency_rates
  add constraint UKs2ntj203sxk6egxc5b03qjkcn unique (currency_source, currency_type, date);

alter table merchant_info_additional_comment
  add constraint FK3d5torya6whupwex7xpscy5fm
  foreign key (merchant_info_id)
  references merchant_info;