name: Build artifact

on:
  push:
    branches: [ aws ]
  pull_request:
    branches: [ aws ]

jobs:
  # build packages
  build_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          ref: aws

      - name: Print new build number
        run: echo "Build number is [$GITHUB_RUN_NUMBER]"

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.m2
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Make executeable
        run: chmod +x ./gradlew

      - name: Run build
        run: ./gradlew clean build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Uploading build
        uses: actions/upload-artifact@v3
        with:
          name: sync-app.jar
          path: /home/runner/work/sync-app/sync-app/build/libs/sync-app.jar

  # build and push image
  build_image:
    needs: build_packages
    runs-on: ubuntu-latest

    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          ref: aws

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: sync-app.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List of files
        run: ls -lh

      - name: Set up build NR
        run: echo "NR=$((${{github.run_number}} + 1067))" >> $GITHUB_ENV

      - name: Print NR
        run: echo ${{ env.NR }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            bobobo/pb-integration-aws:latest
            bobobo/pb-integration-aws:${{env.NR}}